let handler = async (m, { conn }) => {
  m.reply(`
*┏━_͜͡-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡⚘-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡⚘-͜͡-͜͡-͜͡-͜͡-͜͡━┓*

❥ *"${pickRandom(global.piropo)}"*

*┗━_͜͡-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡⚘-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡⚘-͜͡-͜͡-͜͡-͜͡-͜͡━┛*
`)
}

handler.tags = ['fun']
handler.command = handler.help = ['piropo']
handler.fail = null

export default handler

function pickRandom(list) {
  return list[Math.floor(list.length * Math.random())]
}

global.piropo = [
  "Si tu cuerpo fuera cárcel y tus labios cadena, qué bonito lugar para pasar mi condena.",
  "¡Lo tuyo es un dos por uno, además de guapa eres simpática!",
  "Fíjate como es la ciencia que ahora hasta hacen bombones que andan.",
  "Por la luna daría un beso, daría todo por el sol, pero por la luz de tu mirada, doy mi vida y corazón.",
  "Si yo fuera un avión y tú un aeropuerto, me la pasaría aterrizando por tu hermoso cuerpo.",
  "Tantas estrellas en el espacio y ninguna brilla como tú.",
  "Me gusta el café, pero prefiero tener-té.",
  "No eres Google, pero tienes todo lo que yo busco.",
  "Mis ganas de ti no se quitan, se acumulan.",
  "Te regalo esta flor, aunque ninguna será jamás tan bella como tú.",
  "Cuando te multen por exceso de belleza, yo pagaré tu fianza.",
  "Si cada gota de agua sobre tu cuerpo es un beso, entonces quiero convertirme en aguacero.",
  "Estás como para invitarte a dormir, y no dormir.",
  "Si tu cuerpo fuera cárcel y tus brazos cadenas, ese sería el lugar perfecto para cumplir condena.",
  "¿Cómo podría querer irme a dormir si estás tú al otro lado de la pantalla?",
  "Quisiera ser hormiguita para subir por tu balcón y decirte al oído: guapa, bonita, bombón.",
  "En mi vida falta vida, en mi vida falta luz, en mi vida falta alguien y ese alguien eres tú.",
  "Señorita, si supiera nadar, me tiraría en la piscina de tus ojos desde el trampolín de sus pestañas.",
  "Señorita disculpe, pero la llaman de la caja... —¿Qué caja?... —De la caja de bombones de la que te escapaste.",
  "Eres tan hermosa que te regalaría un millón de besos y si no te gustasen te los aceptaría de regreso.",
  "Eres tan bonita que Dios bajaría a la tierra tan solo para verte pasar.",
  "¡Eres como una cámara Sony! Cada vez que la miro no puedo evitar sonreír.",
  "En una isla desierta me gustaría estar y solo de tus besos poderme alimentar.",
  "Si fueras lluvia de invierno, yo cerraría el paraguas para sentirte en mi cuerpo.",
  "Me gustas tanto, tanto, que hasta me gusta estar preso en las redes de tu encanto.",
  "Si te pellizco seguro que te enojas, pero si me pellizcas tú, seguro que me despierto.",
  "No son palabras de oro ni tampoco de rubí; son palabras de cariño que compongo para usted.",
  "Te invito a ser feliz, yo pago.",
  "Cuando caminas no pisas el suelo, lo acaricias.",
  "Nos veríamos lindo en un pastel de boda juntos.",
  "Tantas formas de vida y yo solo vivo en tus ojos.",
  "¿A qué número llamo si quiero marcarte de por vida?",
  "Me gustas tanto que no sé por dónde empezar a decírtelo.",
  "Todos se quedan con tu físico, pero yo prefiero tu corazón.",
  "Hola, si te gustan los idiomas, cuando quieras te enseño mi lengua.",
  "Dime por dónde paseas para besar el suelo que pisas, ¡preciosidad!",
  "Tu belleza me enciega porque viene desde tu corazón y se refleja en tus ojos.",
  "Eres de esa clase de personas por las cuales a las estrellas se les piden deseos.",
  "Si alguna vez te han dicho que eres bella, te mintieron: no eres bella, eres hermosa.",
  "Celeste es el cielo, amarilla la nata y negros son los ojos de la chica que me mata.",
  "Si yo fuera Colón, navegaría día y noche para llegar a lo más profundo de tu corazón.",
  "Cinco calles he cruzado, seis con el callejón; solo me falta una para llegar a tu corazón.",
  "Si fueras mi novia me volvería ateo. ¿Por qué? Porque no tendría nada más que pedirle a Dios.",
  "A una hermosa niña acompañada de la madre: ¡Qué linda flor, lástima que venga con la maceta!",
  "Si me dedicas una sonrisa pasas de ser linda a perfecta.",
  "¿Qué pasó en el cielo que se están cayendo los ángeles?",
  "¡Te voy a poner una multa! ¿Por qué? Por exceso de belleza.",
  "Cómo se habrán querido tus padres... por haberte hecho tan bonita.",
  "¿Por qué el cielo está nublado? Porque todo el azul está en tus ojos.",
  "¿Tienes alguna herida, guapa? Tiene que ser duro caerse del cielo.",
  "Tus ojos son verdes, los míos café; los míos te quieren, los tuyos no sé.",
  "Cuando el día se nubla, no extraño al sol, porque lo tengo en tu sonrisa.",
  "Pasa una mujer y dice adiós... —A Dios lo vi cuando me miraron tus ojos.",
  "En otras partes del mundo se están quejando, porque el sol está acá nada más.",
  "Aprovecha que estoy en rebaja, guapa, y te dejo dos besos por el precio de uno.",
  "Dios se pasó al crearte a ti.",
  "Al amor y a ti los conocí al mismo tiempo.",
  "Si la belleza fuese tiempo, tú serías 24 horas.",
  "Si algún día te pierdes, búscate en mis pensamientos.",
  "Si amarte fuera pecado, tendría el infierno asegurado.",
  "Eres lo único que le falta a mi vida para ser perfecta.",
  "Eres la única estrella que falta en el cielo de mi vida.",
  "Ahora que te conozco, no tengo nada más que pedirle a la vida.",
  "Voy a tener que cobrarte alquiler, porque desde que te vi no has dejado de vivir en mis sueños.",
  "Me gustaría ser tu almohada, para que me abraces todas las mañanas.",
  "No te digo palabras bonitas, sino un verso sincero: mi amor por ti es infinito y mi corazón es verdadero.",
  "Lo que siento por ti es tan inmenso que, para guardarlo, me haría falta otro universo.",
  "Las matemáticas siempre dicen la verdad: tú y yo juntos hasta la eternidad.",
  "Qué fácil sería cumplir una condena si tu cuerpo fuera cárcel y tus brazos cadenas.",
  "Mi madre me dijo que no debía pecar, pero por ti estoy dispuesta a confesarme.",
  "No se trata del whisky ni la cerveza; eres tú quien se me ha subido a la cabeza.",
  "De noche brilla la luna y de día brilla el sol, pero tus ojos bonitos alumbran mi corazón.",
  "No me busques, prefiero seguir perdido en tu mirada.",
  "Unos quieren el mundo, otros quieren el sol, pero yo solo quiero un rincón en tu corazón.",
  "Te dejaré de amar a partir del día que encuentre el alfiler que ahora tiro al mar.",
  "Bienaventurados los borrachos, porque ellos te verán dos veces.",
  "Cómo avanza la ciencia si ya las flores caminan.",
  "Tanta curva y yo sin frenos.",
  "Si Adán por Eva se comió una manzana, yo por ti me comería una frutería.",
  "Si yo fuera astronauta te llevaría a Plutón, pero como no lo soy te llevo siempre en mi corazón.",
  "T�� debes ser atea, porque estás como quieres y no como Dios manda.",
  "Si que está avanzada la ciencia: que hasta los bombones caminan.",
  "¿De qué juguetería te escapaste? ¡Muñeca!",
  "Ayer pasé por tu casa y me tiraste un ladrillo… mañana pasaré de nuevo para construirte un castillo.",
  "¿Te dolió caer del cielo… angelito?",
  "Tu madre debía de ser pastelera porque un bombón como tú no lo hace cualquiera.",
  "Tu papá debe ser un pirata, porque tú eres un tesoro.",
  "Siempre escucho decir a las personas que Disneyland es el lugar más feliz del mundo. Pero me pregunto: ¿si han estado alguna vez a tu lado?",
  "Por algún motivo, hoy me sentía un poco mal. Pero cuando te vi llegar, me excitaste y se me fue todo el malestar.",
  "¿Sabes si hay un aeropuerto por aquí cerca o mi corazón está despegando?",
  "¿Tu papá era boxeador? ¿No? ¡Porque maldita sea, tengo que decírtelo! Eres un nocaut (K.O.).",
  "¡Oh, Dios mío! ¿Tienes un corazón extra? Porque el mío acaba de ser robado.",
  "Aparte de ser increíblemente sexy, ¿a qué te dedicas?",
  "¿Acaba de salir el sol o simplemente me sonreíste?",
  "Tienes que besarme si me equivoco: ¿los dinosaurios todavía existen?",
  "Oye, eres linda y yo lindo. Juntos seríamos bastante lindos.",
  "Estoy seguro que tu nombre debe ser Google. ¿Sabes por qué? Porque tienes absolutamente todo lo que estaba buscando.",
  "Estoy seguro que tu padre es extraterrestre. ¡Porque no he visto nada como tú en la Tierra!",
  "Por favor no te asustes con esta pregunta pero… ¿tu padre era un ladrón? Porque alguien robó las estrellas del cielo y las puso en tus ojos, bebota.",
  "¿Tienes un lápiz y una goma? Porque quiero borrar tu pasado y escribir nuestro futuro.",
  "No necesitas llaves para volverme loco.",
  "Lo siento, pero me debes un trago. ¿Por qué? Porque cuando te miré, me dejaste hipnotizado y tiré mi trago.",
  "Debes ser una escoba, porque acabas de derribarme.",
  "Adelante, siente mi camisa. ¡Está hecha de material de novio!",
  "¿Crees en el amor a primera vista? ¿O tendría que pasar frente a ti de nuevo?",
  "Estoy estudiando sobre fechas importantes en la historia. ¿Quieres ser una de ellas?",
  "Discúlpame pero... ¿tú eres un préstamo? ¡Porque tienes todo mi interés!",
  "Si soy vinagre, entonces debes ser bicarbonato de sodio. ¡Porque me haces sentir burbujeante por dentro!",
  "Por un segundo pensé que estaba muerto y me había ido al cielo. Ahora veo que todavía vivo, pero el cielo me ha sido traído.",
  "¿Puedo pedirte un beso? Te juro que te lo devolveré.",
  "Por favor deja de ser tan dulce, ¡me estás dando dolor de muelas!",
  "¡Eres como mi taza de café favorita: caliente y para relamerse los labios!",
  "¿Eres una cámara? Porque cada vez que te miro, sonrío.",
  "¿Sabes qué te quedaría realmente bien? Yo.",
  "No necesito Twitter, ya te estoy siguiendo.",
  "Tienes que darme tu nombre para saber qué gritar esta noche.",
  "Es un hecho: ya te encuentras en mi lista de cosas por hacer esta noche; imposible que te me escapes.",
  "¿Sabes qué hay en el menú de rico? Bueno… tú y yo, baby.",
  "Tus labios se ven muy solitarios y secos. Permíteme presentarte los míos.",
  "Si nada dura para siempre, ¿serás mi nada?",
  "¿Tienes un nombre? ¿O puedo llamarte mía?",
  "¿Has estado cubierta de abejas recientemente? Solo lo asumí, porque te ves más dulce que la miel.",
  "Debe haber algo mal en mis ojos: no puedo dejar de mirarte.",
  "Eres como el fuego, porque estás súper caliente.",
  "Con mis amigos apostamos a que no podría entablar una conversación con la mujer más guapa del bar. Bueno, ¿y ahora qué deberíamos hacer con su dinero?",
  "Bueno, aquí estoy: tu deseo fue cumplido. Ahora bien… ¿cuáles son tus otros 2 deseos para el genio de la lámpara?",
  "Mira… no soy matemático, pero soy bastante bueno con los números. ¿Por qué no me das tu número y te enseño lo que puedo hacer con él?",
  "¿Eres una viajera en el tiempo? ¡Porque te veo en mi futuro!",
  "Si tú y yo fuéramos calcetines, ¡haríamos un gran par!",
  "Aparte de ser increíblemente hermosa, ¿a qué te dedicas?",
  "¿Quieres una pasa? ¿No? Bueno, ¿qué tal una cita?",
  "Puede que no sea fotógrafo, pero puedo imaginarnos totalmente juntos.",
  "Tú debes ser una maga. Es raro, porque cada vez que te miro, mágicamente todos desaparecen.",
  "Quiero que nuestro amor sea como el número Pi: irracional y sin fin.",
  "Estoy escribiendo un libro sobre todas las cosas buenas de la vida y tú estás en la primera página.",
  "Tú eres la razón por la que incluso Santa tiene una lista traviesa.",
  "¿Dónde te he visto antes? Oh sí, ahora lo recuerdo: estabas en el diccionario junto a la palabra MAGNÍFICO.",
  "No siempre fui religioso, pero lo soy ahora, porque eres la respuesta a todas mis oraciones.",
  "Debes de estar exhausto: has estado corriendo por mi mente todo el día.",
  "Hay algún problema con mi teléfono: no tiene tu número en él.",
  "Soy nuevo en la ciudad. ¿Podría darme indicaciones para llegar a su apartamento?",
  "¿Eres mi cargador de teléfono? Porque sin ti me moriría.",
  "Disculpe, ¿sabe cuánto pesa un oso polar? ¿No? Yo tampoco, pero rompe el hielo.",
  "Imagina esto unos segundos: ¿no crees que nos veríamos tiernos en un pastel de bodas con nuestras caras en él?",
  "Solamente una cosa cambiaría de ti, y ese es tu apellido por el nuestro.",
  "¡Lo siento! Pero tengo que pedirte que te vayas de aquí: estás haciendo quedar mal a las otras chicas. ¿No te da vergüenza?",
  "Perdona pero, ¿podrías sostener mi brazo? Así puedo decirles a mis amigos que me ha tocado un ángel en la tierra.",
  "Hola, estoy escribiendo una guía telefónica, ¿puedo darme su número?",
  "Hola, ¿te conozco? Porque te pareces demasiado a mi futura novia.",
  "Entonces, cuando nuestros amigos nos pregunten cómo nos conocimos, ¿qué les diremos?",
  "¿Cuáles son tus prioridades el domingo?: ¿dormir, ejercitarte o una avalancha de mimos?",
  "Mie@»!# Creo que he perdido mi número, ¿puedo tener tu número?",
  "Si Internet Explorer es tan valiente como para pedirme que sea mi navegador predeterminado, yo también soy lo suficientemente valiente para invitarte a salir.",
  "¿Ves a mi amigo allá? Él pregunta si crees que soy lindo.",
  "¡Dios! Eres tan hermosa que lograste que me olvidara lo que iba a decirte.",
  "Hola, mi nombre es [tu nombre], pero puedes llamarme esta noche.",
  "Oye, ¿tienes un par de minutos para que ligue contigo?",
  "¿Eres un punto de acceso Wi‑Fi? Porque siento una conexión.",
  "No busques más: en una escala del 1 al 10, eres un 9… seguro, y yo soy el 1 que necesitas para el 10.",
  "No sé qué está pasando: ¿hubo un terremoto o simplemente sacudiste mi mundo?",
  "¿De casualidad eres religiosa? Porque eres la respuesta a todas mis oraciones.",
  "¿Eres Netflix? Porque podría quedarme despierto observándote cuatro horas.",
  "Tengo que decírtelo: tú te pareces mucho a mi próxima alma gemela.",
  "¿Puedo tener tu foto para mi lista de navidad de regalos que pediré a Santa?",
  "Si tú y yo fuéramos calcetines seguro que haríamos un gran par.",
  "Espero que no te moleste si te sigo; mi madre siempre me dijo que siguiera mis sueños.",
  "Acabas de dejar caer algo… mi mandíbula.",
  "He estado mirando tu foto de perfil durante años. Todavía no puedo parar.",
  "¿Eres una obra de arte? Porque me gustaría clavarte en mi pared. ¡Guau!",
  "Después de mirarte durante 0,7 segundos, me duele la cabeza. Debe ser dolor de cabeza por mirar algo tan brillante.",
  "Eres el tipo de chica que mi mamá me dijo que le trajera. ¿Te gustaría ir a verla conmigo?",
  "Hola, mi nombre es Will… soy la gran voluntad de Dios solo para ti.",
  "Tu rostro es perfecto… como una obra de arte bien armada. Dios hizo un gran trabajo contigo.",
  "Te miro y solo puedo imaginar lo feliz que será mi vida despertando a tu lado cada mañana.",
  "Tus ojos son hermosos. ¿Llevas lentes de contacto?",
  "¿Puedo compartir una historia contigo?",
  "¿Me estabas sonriendo o acababa de salir el sol?",
  "Tus ojos me han dicho muchas cosas, pero lo que no me dicen es tu nombre.",
  "Vi un jardín esta mañana y pensé que era el más hermoso… hasta que te conocí.",
  "Debo estar en el cielo porque estoy mirando a un ángel.",
  "Debe haber algo mal en mis ojos: no puedo quitártelos de encima.",
  "Nunca jugaría al escondite contigo, porque alguien como tú es imposible de encontrar.",
  "Puedes caer del cielo, puedes caer de un árbol, pero la mejor manera de caer… es enamorada de mí.",
  "¿Tienes un nombre o simplemente puedo llamarte mía?",
  "Me voy a quejar a Spotify porque no eres el single más popular de esta semana.",
  "Las rosas son rojas como mi cara, pero eso solo pasa cuando estoy cerca de ti.",
  "Me gustaría invitarte al cine, pero no permiten bocadillos."
]
